# Local dev paths ? override via environment variables in production
csv.path.orders=C:/Users/sgrch/Desktop/central-learning/data-engineering/dataFiles/csv/input/orders.csv
parquet.path.orders=C:/Users/sgrch/Desktop/central-learning/data-engineering/dataFiles/parquet/orders
parquet.path.partitioned.orders=C:/Users/sgrch/Desktop/central-learning/data-engineering/dataFiles/parquet/partitioned-orders