# Local dev paths ? override via environment variables in production
#CSVs
csv.path.orders=C:/Users/sgrch/Desktop/central-learning/data-engineering/data-file/csv/input/orders.csv
csv.path.customers=C:/Users/sgrch/Desktop/central-learning/data-engineering/data-file/csv/input/customers.csv
csv.path.orders_v2=C:/Users/sgrch/Desktop/central-learning/data-engineering/data-file/csv/input/orders_v2.csv
csv.path.orders_v3=C:/Users/sgrch/Desktop/central-learning/data-engineering/data-file/csv/input/orders_v3.csv
csv.path.orders_dirty = C:/Users/sgrch/Desktop/central-learning/data-engineering/data-file/csv/input/orders_dirty.csv
csv.path.customers_current=C:/Users/sgrch/Desktop/central-learning/data-engineering/data-file/csv/input/customers_current.csv
csv.path.orders_dupes=C:/Users/sgrch/Desktop/central-learning/data-engineering/data-file/csv/input/orders_dupes.csv

#JSON
json.path.transactions=C:/Users/sgrch/Desktop/central-learning/data-engineering/data-file/json/input/transactions.json








#Parquet
parquet.path.orders=C:/Users/sgrch/Desktop/central-learning/data-engineering/data-file/parquet/orders
parquet.path.partitioned.orders=C:/Users/sgrch/Desktop/central-learning/data-engineering/data-file/parquet/partitioned-orders
parquet.path.enriched.orders= C:/Users/sgrch/Desktop/central-learning/data-engineering/data-file/parquet/enriched_orders
parquet.path.clean.orders=C:/Users/sgrch/Desktop/central-learning/data-engineering/data-file/parquet/orders_clean
parquet.path.quarantine.orders= C:/Users/sgrch/Desktop/central-learning/data-engineering/data-file/parquet/orders_quarantine
parquet.path.transactions=C:/Users/sgrch/Desktop/central-learning/data-engineering/data-file/parquet/transactions
parquet.path.orders_dupes-removed = C:/Users/sgrch/Desktop/central-learning/data-engineering/data-file/parquet/deDupes